apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: secretservice
    app: secretservice
  name: secretservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secretservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secretservice
        app: secretservice
    spec:
      containers:
      - name: secretservice
        image: us-east1-docker.pkg.dev/hw-beta-centari-2024-06/secrethw/secretservice:latest
        ports:
        - name: web
          containerPort: 8080
        - name: metrics
          containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: secretservice
  labels:
    app.kubernetes.io/name: secretservice
    app: secretservice
spec:
  type: LoadBalancer
  selector:
    app: secretservice
  ports:
    - name: http
      port: 80
      targetPort: 8080