apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-server
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'secretservice'
        static_configs:
          - targets: ['secretservice:7070']
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - 'alertmanager.monitoring.svc.cluster.local:9093'
    rule_files:
      - /etc/prometheus/rules/alerts.yml

  alerts.yml: |
    groups:
    - name: decryption_errors
      rules:
      - alert: DecryptionError
        expr: function_times{name="__Service__Decrypt",kind="failure",scope="_main",field="count"} > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Decryption error detected"
          description: "A decryption error has occurred in the __Service__Decrypt function."