# .github/workflows/build-and-push-to-gcr.yaml
name: Build and Push to GCR

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/build-and-push-to-gcr.yaml'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCR_HOSTNAME: gcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GKE_SA_EMAIL }}

    - name: Build and push Docker image to GCR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: $GCR_HOSTNAME/$PROJECT_ID/secretservice:latest
        file: ./backend/Dockerfile
        context: ./backend