# .github/workflows/build-and-push-to-gcr.yaml
name: Build and Push to GCR

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/build-and-push-to-gcr.yaml'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GAR_HOSTNAME: us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/secrethw

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Build and push Docker image to Google Artifact Registry
      run: |
        echo $GCP_SA_KEY | docker login -u _json_key_base64 --password-stdin https://us-east1-docker.pkg.dev
        docker build -t secretservice:latest .
        docker tag secretservice us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/secrethw/secretservice:latest
        docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/secrethw/secretservice:latest